# Generated by Django 3.0.7 on 2020-06-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url_path',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
