# Generated by Django 3.0.7 on 2020-06-25 17:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urls', '0002_auto_20200625_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records', django.contrib.postgres.fields.jsonb.JSONField()),
                ('records_unique_user', django.contrib.postgres.fields.jsonb.JSONField()),
                ('url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='urls.Url')),
            ],
        ),
    ]
