# Generated by Django 3.0.7 on 2020-06-25 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytic',
            name='records_unique_user',
        ),
    ]
